controlNamespace: canfar-perfpulse
workloadNamespace: canfar-workloads
serviceAccount:
  create: false
  name: canfar-perfpulse
image:
  repository: images.opencadc.org/platform/perfpulse
  tag: v0.1.14 # x-release-please-version
  pullPolicy: Always
workload:
  kubernetesImage: ""
  image: images.canfar.net/skaha/stress-ng:latest
campaign:
  type: benchmark
  confirmStress: false
  confirmHighUsers: false
  testid: null
  totalJobs: null
  logicalUsers: null
  visibilityGateSeconds: 120
  completionTimeoutSeconds: 259200
  submissionJitterMaxMs: 1000
  pollJitterMaxMs: 1000
  profile: campaign
  scenario: many-small-users
otlp:
  credentialsSecretName: perfpulse-otlp-credentials
  endpoint: kube-prometheus-stack-prometheus.monitoring:9090
  urlPath: /api/v1/otlp/v1/metrics
skaha:
  credentialsSecretName: perfpulse-skaha-auth
  requestTimeoutSeconds: 600
  apiUrl: >-
    http://canfar-skaha-staging-skaha-tomcat-svc.canfar-system-staging.svc.keel-prod.local:8080/skaha/v1
  loginUrl: https://ws-cadc.canfar.net/ac/login
surfaces:
  - k8s-direct
  - k8s-kueue
  - skaha
