{{ include "perfpulse.validateCampaign" . }}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "perfpulse.serviceAccountName" . }}
  namespace: {{ .Values.controlNamespace }}
  labels:
{{ include "perfpulse.labels" . | indent 4 }}
---
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "perfpulse.workloadWriterName" . }}
  namespace: {{ .Values.workloadNamespace }}
  labels:
{{ include "perfpulse.labels" . | indent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "delete", "get", "list"]
  - apiGroups: ["kueue.x-k8s.io"]
    resources: ["workloads"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "perfpulse.workloadWriterName" . }}
  namespace: {{ .Values.workloadNamespace }}
  labels:
{{ include "perfpulse.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "perfpulse.workloadWriterName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "perfpulse.serviceAccountName" . }}
    namespace: {{ .Values.controlNamespace }}
